### ISSUE TITLE
SZSは本当にZですか?

### ISSUE THREAD

**Issue by Nayuta-Ito** [qniapp/quantattack#116]
ゲームサイト内で紹介されている[Wikipediaの記事](https://en.m.wikipedia.org/wiki/Quantum_logic_gate) をもとに行列の計算をすると、SZS=Iとなります。ゲーム内でSZS=Zになるのはバグでしょうか? それとも、私が量子力学特有の奇妙な何かを見逃しているのでしょうか?

**Comment by yasuhito** [comment]
すいませんイシューが来るとは思っておらず気付いていませんでした。
こちらそのとおりでバグです。すぐに修正 PR を出します。

**Comment by Nayuta-Ito** [comment]
突然のissue申し訳ありませんでした。
こちらもどこにお問い合わせを出してよいかわからず、GitHubを見つけたのでそこに書いたという次第です。
修正ありがとうございます。

**Comment by yasuhito** [comment]
いえ! そういう意味ではなくわざわざ GitHub をみつけていただいて報告までありがとうございます。
また何かおかしな挙動があればいつでも教えてください。
